### ISSUE TITLE
uvicorn `Child process died`

### ISSUE THREAD

**Issue by ch-sander** [epoz/shmarql#21] opened 2024-08-25 21:28 UTC
https://github.com/epoz/shmarql/blob/8811fddb8f7f4b104e504437564616cd2f290776/Dockerfile#L39

When loading from store (and _only if_ building the Docker image locally) the worker fails (snippet):

```
shmarql_dev  | 2024-08-25 21:22:53 DEBUG    Opening store from /data/store
shmarql_dev  | 2024-08-25 21:22:53 DEBUG    Opening store from /data/store
shmarql_dev  | 2024-08-25 21:22:53 DEBUG    Opening store read-only
shmarql_dev  | 2024-08-25 21:22:53 DEBUG    Opening store read-only
shmarql_dev  | 2024-08-25 21:22:53 DEBUG    Opening store from /data/store
shmarql_dev  | 2024-08-25 21:22:53 DEBUG    Opening store from /data/store
shmarql_dev  | 2024-08-25 21:22:53 DEBUG    Opening store read-only
shmarql_dev  | 2024-08-25 21:22:53 DEBUG    Opening store read-only
shmarql_dev  | INFO:     Waiting for child process [8]
shmarql_dev  | INFO:     Child process [8] died
shmarql_dev  | INFO:     Waiting for child process [9]
shmarql_dev  | INFO:     Child process [9] died
```

Loading from ttl works.

It also works if I run just one worker per `CMD ["uvicorn", "--workers", "1", "--host", "0.0.0.0", "--port", "8000", "app:app", "--log-level", "debug" ]`

Very odd. Any idea why that is?

Maybe the uvicorn library has changed meanwhile (and is on an older version in origin docker image at _ghcr.io/epoz/shmarql:latest_)?
https://github.com/epoz/shmarql/blob/8811fddb8f7f4b104e504437564616cd2f290776/requirements.txt#L3

**Comment by ch-sander** [comment] 2024-08-25 21:38
`Running uvicorn 0.29.0 with CPython 3.9.7 on Linux` for `ghcr.io/epoz/shmarql:latest`. If changed in https://github.com/epoz/shmarql/blob/8811fddb8f7f4b104e504437564616cd2f290776/requirements.txt#L3, problem solved.

Still, something to look out for.

**Comment by epoz** [comment] 2024-08-26 17:34
In uvicorn 0.30 a [new multiprocess manager](https://github.com/encode/uvicorn/pull/2183) was released, and this caused breakage in shmarql with the uvicorn parent process just dying.
I had to pin the uvicorn to 0.29 at the time, as all newer versions were showing this behaviour.

It looks like newer versions have now fixed this, so we can probably start using the newer versions, but we will have to pin to something a bit higher. To be tested...

**Closed** 2024-09-30 14:38 UTC

**Comment by ahirner** [comment] 2024-10-15 20:36
[I see it pinned ](https://github.com/epoz/shmarql/commit/78426dba49d408687e93499912a2cec589ee2b4f) kept uvicorn pinned to `0.29`.

> It looks like newer versions have now fixed this, so we can probably start using the newer versions, but we will have to pin to something a bit higher. To be tested...

Did you test higher versions @epoz ?

**Comment by epoz** [comment] 2024-10-16 10:16
@ahirner - not extensively, there was no need for me to use a higher version yet.

Please note that I have started working on a [re-boot of shmarql in fasthtml](https://github.com/epoz/shmarql/tree/fasthtml) which brings several improvements.

May I ask, are you using shmarql for anything that I should be aware of with regards to breaking changes, or backwards compatibility? To date I thought there was not that many other users.

**Comment by ahirner** [comment] 2024-10-16 10:30
Thanks! We are see the same error in a django app of ours. `0.29` can't restart workers (ignores SIGHUP), workers with later versions die. I was mainly looking for hints how to reproduce that, unfortunately no user of `shmarql` :)

PS: as we speak, we found that [granian](https://github.com/emmett-framework/granian) doesn't suffer from dying workes and can restart them gracefully.

**Comment by epoz** [comment] 2024-10-16 10:35
Ah, clear... 
FastAPI did work with later versions of uvicorn when I tested it informally, so yes, it seemed this was sorted. But to be on the safe side I left the version pinned in my repo.
